[build]
  base = "."  # Diretório base onde as dependências são instaladas e o comando de construção é executado
  publish = "."  # Diretório onde os arquivos do site são armazenados após a construção
  command = "npm run build"  # Comando de construção para compilar o projeto

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
